pipeline {
    agent any

    environment {
        IMAGE_NAME = "demo-java-app"
        DOCKERHUB_CREDS = credentials('dockerhub-creds')
        DOCKERHUB_USER = "8438"
    }

    stages {

        stage('Build Maven') {
            steps {
                dir('Project/src') {
                    sh 'mvn clean package'
                }
            }
        }

        stage('Trivy File Scan') {
            steps {
                dir('Project/src') {
                    sh 'trivy fs .'
                }
            }
        }

        stage('Docker Build') {
            steps {
                dir('Project/src') {
                    sh 'docker build -t $IMAGE_NAME .'
                }
            }
        }

        stage('Trivy Image Scan') {
            steps {
                sh 'trivy image $IMAGE_NAME'
            }
        }

        stage('Docker Tag') {
            steps {
                sh 'docker tag $IMAGE_NAME $DOCKERHUB_USER/demo-java-app:v1'
            }
        }

        stage('Docker Push') {
            steps {
                sh '''
                echo $DOCKERHUB_CREDS_PSW | docker login \
                -u $DOCKERHUB_CREDS_USR --password-stdin
                '''

                sh 'docker push $DOCKERHUB_USER/demo-java-app:v1'
            }
        }

        // stage('Terraform Init') {
        //     steps {
        //         dir('Project/terraform') {
        //             sh 'terraform init'
        //         }
        //     }
        // }

        // stage('Terraform Apply') {
        //     steps {
        //         dir('Project/terraform') {
        //             sh 'terraform apply -auto-approve'
        //         }
        //     }
        // }

        stage('Deploy Container') {
            steps {
                sh '''
                docker run -d --name demo-container02 \
                -p 8082:8080 \
                $DOCKERHUB_USER/demo-java-app:v1
                '''
            }
        }
    }
}
